# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import xlsxOpenpyxl
import quarryDB
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1032, 686)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(240, 140, 511, 331))

        # 读取excel 生成二维lists读取表头
        lists = xlsxOpenpyxl.read_excel_xlsx('../test4.xlsx', 'Sheet1')
        print(lists)
        headName = quarryDB.get_head_name('test')
        print(headName)

        self.tableWidget.setObjectName("tableWidget")

        #设置表格行列数
        self.tableWidget.setColumnCount(len(lists[0]))
        self.tableWidget.setRowCount(len(lists))
        #配置表头
        self.tableWidget.setHorizontalHeaderLabels(headName)
        #填充数据
        for i in range(len(lists)):
            for j in range(len(lists[0])):
                self.tableWidget.setItem(i, j, QTableWidgetItem(lists[i][j]) )

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)






    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
import sys


from PyQt5.QtWidgets import QApplication, QMainWindow, QTableWidgetItem

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())